#!/bin/sh

delete_containers () {
  docker stop ory-hydra ory-postgres
  docker rm ory-hydra ory-postgres
}

run_postgres_container () {
  sudo docker run \
    --network hydranet \
    --name ory-postgres \
    -e POSTGRES_USER=hydra \
    -e POSTGRES_PASSWORD=secret \
    -e POSTGRES_DB=hydra -p 5431:5432 \
    -d postgres:9.6
}

run_hydra_migrations () {
  sudo docker run -it --rm \
    --network hydranet \
    oryd/hydra:v1.0.0-beta.5 \
    migrate sql $DATABASE_URL
}

run_hydra_container () {
  sudo docker run -d \
    --name ory-hydra \
    --network hydranet \
    -p 9000:4444 \
    -e SYSTEM_SECRET=$SYSTEM_SECRET \
    -e DATABASE_URL=$DATABASE_URL \
    -e OAUTH2_ISSUER_URL=https://localhost:9000/ \
    -e OAUTH2_CONSENT_URL=http://localhost:3000/consent \
    -e OAUTH2_LOGIN_URL=http://localhost:3000/login \
    -e FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password \
    oryd/hydra:v1.0.0-beta.5 serve
}

register_hydra_dashboard_client () {
  docker run --rm -it \
    -e HYDRA_URL=https://ory-hydra:4444 \
    --network hydranet \
    oryd/hydra:v1.0.0-beta.5 \
    clients create --skip-tls-verify \
      --id hydra-dashboard \
      --secret hydra-dashboard-secret \
      --grant-types authorization_code,refresh_token,client_credentials,implicit \
      --response-types token,code,id_token \
      --scope openid,offline,hydra.clients \
      --callbacks http://localhost:3000/callback
}

reset () {
  delete_containers
  run_postgres_container
  run_hydra_migrations
  run_hydra_container # OAuth2.0 Server

  echo "waiting for hydra server ..."
  sleep 15

  register_hydra_dashboard_client # OAuth2.0 Client Placeholder for hydra-dashboard
}

export DATABASE_URL=postgres://hydra:secret@ory-postgres:5432/hydra?sslmode=disable
export SYSTEM_SECRET=$(export LC_ALL=C; cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

reset
